/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        foreground: '#171717',
        'mint-900': '#70d7bf',
        'mint-700': '#8ddfcc',
        'midnight-900': '#05141f',
        'midnight-100': '#cdd0d2',
        red: '#ff0900',
        blue: '#4296e4',
        'gray-700': '#37434c',
        'gray-500': '#697278',
        'gray-400': '#82898f',
        'gray-300': '#b4b9bc',
        'gray-200': '#cdd0d2',
        'gray-100': '#e6e8e9',
        'gray-50': '#f6f6f9',
        'gray-10': '#f8f8f8',
      },
      screens: {
        sm: '744px', // 744px 이상
        md: '1024px', // 1024px 이상
        lg: '1440px', // 1440px 이상
      },
      fontSize: {
        base: '16px',
        14: '14px',
        16: '16px',
        18: '18px',
        24: '24px',
        40: '40px',
        48: '48px',
        56: '56px',
      },
      lineHeight: {
        sm: '1.4',
        md: '1.6',
        lg: '1.8',
      },
      spacing: {
        'px-md': '16px',
        'px-lg': '24px',
        'px-xlg': '32px',
        'input-md': '40px',
        'input-md-fsize': '16px',
        'textarea-md': '140px',
        'space-xsm': '8px',
        'space-xsm2': '8px',
        'space-sm': '12px',
        'space-sm2': '12px',
        'space-md': '16px',
        'space-md2': '20px',
        'space-md3': '20px',
        'space-box': '48px',
        'space-box2': '120px',
        'heading-2': '20px',
        'heading-2-margin': '48px 0 16px',
        'heading-4': '16px',
        'heading-4-margin': '20px 0 4px',
        'heading-info': '16px',
        'heading-box': '18px',
        'btn-md': '36px',
        'btn-xlg': '48px',
        'btn-xlg2': '40px',
        'btn-xxlg': '72px',
        'btn-xxlg-size': '16px',
        'ic-sm': '20px',
        'ic-md': '24px',
        'ic-lg': '32px',
        'ic-xlg': '40px',
        'ic-xlg2': '32px',
        'ic-xxlg': '64px',
        'header-height': '56px',
        'footer-height': '284px',
        'side-padding': '24px',
        'bottom-padding': '80px',
        'h1-height': '124px',
        'h1-fsize': '24px',
        'h1-fsize-sm': '14px',
        'tab-fsize': 'var(--font-size)',
        'search-bar-width': '100%',
        'gallery-list-length': '1',
        'gallery-list-space': '0',
        'gallery-list-title-space': '12px',
        'gallery-list-title-size': '16px',
        'list-more-size': '14px',
        'board-head-padding': '16px 0',
        'board-body-padding-v': 'var(--px-lg)',
        'board-body-padding-h': '0',
        'board-heading-fsize': '16px',
        'board-media-max-width': '100%',
        'board-footer-col-indent': '12px',
        'faq-list-a-padding-v': '16px',
        'faq-list-a-padding-h': '0',
        'faq-list-a-size': '16px',
        'faq-list-q-padding': '16px 0',
      },
      transitionTimingFunction: {
        primary: 'cubic-bezier(1, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
};
